# Generated by Django 4.2.29 on 2026-04-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cracha', models.CharField(max_length=200, unique=True, verbose_name='Número do Crachá')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtítulo', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(help_text='Descrição do desafio')),
                ('numero', models.PositiveIntegerField(help_text='Número do desafio', unique=True)),
                ('icone', models.CharField(default='bi-trophy', help_text='Classe do Bootstrap Icon', max_length=50)),
                ('pergunta', models.TextField()),
                ('unidade_medida', models.CharField(help_text='Ex: mm, gramas, unidades', max_length=50)),
                ('valor_minimo', models.DecimalField(decimal_places=2, help_text='Valor mínimo aceitável', max_digits=10)),
                ('valor_maximo', models.DecimalField(decimal_places=2, help_text='Valor máximo aceitável', max_digits=10)),
                ('valor_ideal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor ideal/resposta correta', max_digits=10, null=True)),
                ('dica', models.TextField(blank=True, help_text='Dica para o participante', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Quiz disponível para resposta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz/Desafio',
                'verbose_name_plural': 'Quizzes/Desafios',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='core.participante')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.CreateModel(
            name='RespostaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_resposta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('correto', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False, help_text='Indica se o quiz foi completado com sucesso')),
                ('tentativas', models.PositiveIntegerField(default=1)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.participante')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.quiz')),
            ],
            options={
                'verbose_name': 'Resposta do Quiz',
                'verbose_name_plural': 'Respostas dos Quizzes',
                'ordering': ['-data_resposta'],
                'unique_together': {('participante', 'quiz')},
            },
        ),
    ]
