# Generated by Django 4.2.29 on 2026-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
