# Generated by Django 4.2.29 on 2026-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participante_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaquiz',
            name='valor_resposta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
