# Generated by Django 4.2.29 on 2026-04-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_respostaquiz_valor_resposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='subtítulo',
            new_name='subtitulo',
        ),
    ]
