# Generated by Django 4.2.29 on 2026-07-28 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_subtítulo_quiz_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('tipoAtividade', models.CharField(blank=True, max_length=45, null=True)),
                ('horaInicio', models.DateTimeField()),
                ('horaFim', models.DateTimeField()),
                ('imagemBanner', models.CharField(blank=True, max_length=200, null=True)),
                ('limitePessoas', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('emailContato', models.EmailField(blank=True, max_length=50, null=True)),
                ('apoiadores', models.TextField(blank=True, max_length=200, null=True)),
                ('local', models.CharField(blank=True, max_length=45, null=True)),
                ('complementoLocal', models.CharField(blank=True, max_length=45, null=True)),
                ('imagemBanner', models.CharField(blank=True, max_length=200, null=True)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('tipoEvento', models.CharField(blank=True, max_length=45, null=True)),
                ('eventoMultiplo', models.BooleanField(default=False)),
                ('eventoPublico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('cracha', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('Participante', 'Participante'), ('Palestrante', 'Palestrante'), ('Organizador', 'Organizador')], default='Participante', max_length=20, verbose_name='Funcao')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('data_hora_presenca', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividade')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inscricao')),
            ],
            options={
                'verbose_name': 'Participa',
                'verbose_name_plural': 'Participam',
                'ordering': ['funcao'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_resposta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('correto', models.BooleanField(default=False)),
                ('participa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.participa')),
            ],
            options={
                'verbose_name': 'Resposta do Quiz',
                'verbose_name_plural': 'Respostas dos Quizzes',
                'ordering': ['-data_resposta'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('fotoPerfil', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('formacao', models.CharField(blank=True, max_length=200, null=True)),
                ('empresa', models.CharField(blank=True, max_length=45, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='respostaquiz',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='respostaquiz',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='respostaquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='descricao',
        ),
        migrations.DeleteModel(
            name='LogAcesso',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
        migrations.DeleteModel(
            name='RespostaQuiz',
        ),
        migrations.AddField(
            model_name='resposta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.quiz'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.atividade'),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together={('participa', 'quiz')},
        ),
    ]
