# Generated by Django 4.2.29 on 2026-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atividade_evento_inscricao_participa_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagemBanner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
