# Generated by Django 4.2.29 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_evento_imagembanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='imagemBanner',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='complementoLocal',
        ),
        migrations.AddField(
            model_name='atividade',
            name='complementoLocal',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipoAtividade',
            field=models.CharField(choices=[('Colóquio', 'Coloquio'), ('Fórum', 'Forum'), ('Palestra', 'Palestra')], default='Palestra', max_length=20, verbose_name='tipoAtividade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento',
            field=models.CharField(choices=[('Colóquio', 'Coloquio'), ('Fórum', 'Forum'), ('Palestra', 'Palestra')], default='Palestra', max_length=20, verbose_name='tipoEvento'),
        ),
    ]
