# Generated by Django 4.2.29 on 2026-08-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_evento_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipoAtividade',
            field=models.CharField(choices=[('Colóquio', 'Coloquio'), ('Fórum', 'Forum'), ('Palestra', 'Palestra'), ('Oficina', 'Oficina'), ('Mesa Redonda', 'Mesa Redonda'), ('Painel', 'Painel'), ('Minicurso', 'Minicurso'), ('Meetup', 'Meetup'), ('Masterclass', 'Masterclass'), ('Demo Day', 'Demoday'), ('Outro', 'Outro')], default='Palestra', max_length=20, verbose_name='tipoAtividade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento',
            field=models.CharField(choices=[('Colóquio', 'Coloquio'), ('Fórum', 'Forum'), ('Simpósio', 'Simposio'), ('Semana Acadêmica', 'Semana'), ('Encontro', 'Encontro'), ('Congresso', 'Congresso')], default='Semana Acadêmica', max_length=20, verbose_name='tipoEvento'),
        ),
    ]
