# Generated by Django 4.2.29 on 2026-08-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_atividade_tipoatividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='participa',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='participa',
            name='inscricao',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='atividade',
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='participa',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='participante',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Participa',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
