# Generated by Django 4.2.29 on 2026-08-11 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(help_text='Número do desafio', unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('pergunta', models.TextField()),
                ('dica', models.TextField(blank=True, help_text='Dica para o participante', null=True)),
                ('unidade_medida', models.CharField(help_text='Ex: mm, gramas, unidades', max_length=50)),
                ('valor_minimo', models.DecimalField(decimal_places=2, help_text='Valor mínimo aceitável', max_digits=10)),
                ('valor_maximo', models.DecimalField(decimal_places=2, help_text='Valor máximo aceitável', max_digits=10)),
                ('valor_ideal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor ideal/resposta correta', max_digits=10, null=True)),
                ('icone', models.CharField(default='bi-trophy', help_text='Classe do Bootstrap Icon', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, help_text='Quiz disponível para resposta')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_evento.atividade')),
            ],
            options={
                'verbose_name': 'Quiz/Desafio',
                'verbose_name_plural': 'Quizzes/Desafios',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_resposta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('correto', models.BooleanField(default=False)),
                ('participa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app_evento.participa')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app_quiz.quiz')),
            ],
            options={
                'verbose_name': 'Resposta do Quiz',
                'verbose_name_plural': 'Respostas dos Quizzes',
                'ordering': ['-data_resposta'],
                'unique_together': {('participa', 'quiz')},
            },
        ),
    ]
