# Generated by Django 4.2.29 on 2026-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='unidade_medida',
            field=models.CharField(help_text='Ex: mm, gramas, unidades', max_length=50, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='valor_ideal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor ideal/resposta correta', max_digits=10, null=True, verbose_name='Valor Ideal'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, help_text='Valor máximo aceitável', max_digits=10, verbose_name='Valor Máximo'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, help_text='Valor mínimo aceitável', max_digits=10, verbose_name='Valor Mínimo'),
        ),
    ]
