# Generated by Django 4.2.29 on 2026-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0002_alter_quiz_unidade_medida_alter_quiz_valor_ideal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='completo',
            field=models.BooleanField(default=False, help_text='Indica se o quiz foi completado com sucesso'),
        ),
    ]
