# Generated by Django 4.2.29 on 2026-08-11 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('tipoAtividade', models.CharField(choices=[('Colóquio', 'Coloquio'), ('Fórum', 'Forum'), ('Palestra', 'Palestra'), ('Oficina', 'Oficina'), ('Mesa Redonda', 'Mesa Redonda'), ('Painel', 'Painel'), ('Minicurso', 'Minicurso'), ('Meetup', 'Meetup'), ('Masterclass', 'Masterclass'), ('Demo Day', 'Demoday'), ('Outro', 'Outro')], default='Palestra', max_length=20, verbose_name='tipoAtividade')),
                ('complementoLocal', models.CharField(blank=True, max_length=45, null=True)),
                ('horaInicio', models.DateTimeField()),
                ('horaFim', models.DateTimeField()),
                ('limitePessoas', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('emailContato', models.EmailField(blank=True, max_length=50, null=True)),
                ('apoiadores', models.TextField(blank=True, max_length=200, null=True)),
                ('local', models.CharField(blank=True, max_length=45, null=True)),
                ('imagemBanner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('tipoEvento', models.CharField(choices=[('Colóquio', 'Coloquio'), ('Fórum', 'Forum'), ('Simpósio', 'Simposio'), ('Semana Acadêmica', 'Semana'), ('Encontro', 'Encontro'), ('Congresso', 'Congresso')], default='Semana Acadêmica', max_length=20, verbose_name='tipoEvento')),
                ('eventoMultiplo', models.BooleanField(default=False)),
                ('eventoPublico', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('cracha', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evento.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('Participante', 'Participante'), ('Palestrante', 'Palestrante'), ('Organizador', 'Organizador')], default='Participante', max_length=20, verbose_name='Funcao')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('data_hora_presenca', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evento.atividade')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evento.inscricao')),
            ],
            options={
                'verbose_name': 'Participa',
                'verbose_name_plural': 'Participam',
                'ordering': ['funcao'],
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evento.evento'),
        ),
    ]
