# Generated by Django 4.2.29 on 2026-08-18 20:32

import app_evento.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Apoiador',
                'verbose_name_plural': 'Apoiadores',
            },
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipoAtividade',
            field=models.CharField(choices=[('Coloquio', 'Colóquio'), ('Forum', 'Fórum'), ('Palestra', 'Palestra'), ('Oficina', 'Oficina'), ('Mesa Redonda', 'Mesa Redonda'), ('Painel', 'Painel'), ('Minicurso', 'Minicurso'), ('Meetup', 'Meetup'), ('Masterclass', 'Masterclass'), ('DemoDay', 'Demo Day'), ('Outro', 'Outro')], default='Palestra', max_length=20, verbose_name='tipoAtividade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='evento',
            name='apoiadores',
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento',
            field=models.CharField(choices=[('Coloquio', 'Colóquio'), ('Forum', 'Fórum'), ('Simposio', 'Simpósio'), ('SemanaAcademica', 'Semana Acadêmica'), ('Encontro', 'Encontro'), ('Congresso', 'Congresso')], default='SemanaAcademica', max_length=20, verbose_name='tipoEvento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='cracha',
            field=models.CharField(default=app_evento.models.gerar_codigo_cracha, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participa',
            name='atividade',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='inscricao', chained_model_field='evento__inscricao', on_delete=django.db.models.deletion.CASCADE, to='app_evento.atividade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='apoiadores',
            field=models.ManyToManyField(related_name='eventos', to='app_evento.apoiador'),
        ),
    ]
