# Generated by Django 4.2.29 on 2026-09-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0002_apoiador_alter_inscricao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='complementoLocal',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Complemento do Local'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='horaFim',
            field=models.DateTimeField(verbose_name='Hora de Término'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='horaInicio',
            field=models.DateTimeField(verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='limitePessoas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Pessoas'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipoAtividade',
            field=models.CharField(choices=[('Coloquio', 'Colóquio'), ('Forum', 'Fórum'), ('Palestra', 'Palestra'), ('Oficina', 'Oficina'), ('Mesa Redonda', 'Mesa Redonda'), ('Painel', 'Painel'), ('Minicurso', 'Minicurso'), ('Meetup', 'Meetup'), ('Masterclass', 'Masterclass'), ('DemoDay', 'Demo Day'), ('Outro', 'Outro')], default='Palestra', max_length=20, verbose_name='Tipo de Atividade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dataFim',
            field=models.DateField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dataInicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='emailContato',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email de Contato'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagemBanner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento',
            field=models.CharField(choices=[('Coloquio', 'Colóquio'), ('Forum', 'Fórum'), ('Simposio', 'Simpósio'), ('SemanaAcademica', 'Semana Acadêmica'), ('Encontro', 'Encontro'), ('Congresso', 'Congresso')], default='SemanaAcademica', max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
