# Generated by Django 4.2.29 on 2026-09-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_alter_usuario_cpf_alter_usuario_datanascimento_and_more'),
        ('app_evento', '0003_alter_atividade_complementolocal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='app_login.usuario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='apoiadores',
            field=models.ManyToManyField(blank=True, related_name='apoiadores', to='app_evento.apoiador'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app_login.usuario'),
        ),
    ]
