# Generated by Django 4.2.29 on 2026-09-13 16:46

import app_evento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0004_alter_evento_administrador_alter_evento_apoiadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento',
            field=models.CharField(choices=[('Coloquio', 'Colóquio'), ('Forum', 'Fórum'), ('Simposio', 'Simpósio'), ('SemanaAcademica', 'Semana Acadêmica'), ('Encontro', 'Encontro'), ('Congresso', 'Congresso'), ('Outro', 'Outro')], default='SemanaAcademica', max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='cracha',
            field=models.CharField(default=app_evento.models.gerar_codigo_cracha, max_length=7, unique=True),
        ),
    ]
