# Generated by Django 6.0.8 on 2026-09-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0005_alter_evento_tipoevento_alter_inscricao_cracha'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='qrcode_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
