# Generated by Django 4.2.29 on 2026-09-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0006_inscricao_qrcode_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Prêmio')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='app_evento.atividade')),
            ],
            options={
                'verbose_name': 'Prêmio',
                'verbose_name_plural': 'Prêmios',
            },
        ),
    ]
