# Generated by Django 4.2.29 on 2026-09-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0007_premio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='eventoMultiplo',
        ),
    ]
