# Generated by Django 4.2.29 on 2026-08-11 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('formacao', models.CharField(blank=True, max_length=200, null=True)),
                ('empresa', models.CharField(blank=True, max_length=45, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
