# Generated by Django 4.2.29 on 2026-09-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
