# Generated by Django 4.2.29 on 2026-09-01 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_login', '0002_alter_usuario_cpf_alter_usuario_datanascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='participante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
