# Generated by Django 6.0.8 on 2026-09-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_alter_usuario_participante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='participante',
            new_name='user_django',
        ),
    ]
