# Generated by Django 4.2.29 on 2026-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_rename_participante_usuario_user_django'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de Perfil'),
        ),
    ]
